# -*- coding: utf-8 -*-
"""Assignment2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tUNCqGpDzu084JG6Y-gAS6toaCSlLf4B
"""

import numpy as np
import matplotlib.pyplot as plt

# Generate a uniform distribution dataset
data = np.random.uniform(0, 1, 1000)

# Function to plot the histogram and the CDF
def plot_histogram_and_cdf(data, bin_sizes):
    fig, axes = plt.subplots(len(bin_sizes), 2, figsize=(10, 5 * len(bin_sizes)))

    for i, bins in enumerate(bin_sizes):
        # Plot histogram
        axes[i, 0].hist(data, bins=bins, color='blue', alpha=0.7)
        axes[i, 0].set_title(f'Histogram with {bins} bins')
        axes[i, 0].set_xlabel('Value')
        axes[i, 0].set_ylabel('Frequency')

        # Calculate and plot CDF
        count, bin_edges = np.histogram(data, bins=bins)
        cdf = np.cumsum(count) / sum(count)
        axes[i, 1].plot(bin_edges[1:], cdf, color='green', marker='o', linestyle='-')
        axes[i, 1].set_title(f'CDF with {bins} bins')
        axes[i, 1].set_xlabel('Value')
        axes[i, 1].set_ylabel('Cumulative Frequency')

    plt.tight_layout()
    plt.show()

# Different bin sizes for comparison
bin_sizes = [10, 20, 50]

# Plot and compare histograms and their CDFs with different bin sizes
plot_histogram_and_cdf(data, bin_sizes)